access_key_id: AKIAICR6FRQRFATSMPKQ
secret_access_key: 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


development:
  bucket: bookit4pg
  access_key_id: AKIAICR6FRQRFATSMPKQ
  secret_access_key: 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
test:
  bucket: bookit4pg-test
  access_key_id: AKIAICR6FRQRFATSMPKQ
  secret_access_key: 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
production:
  bucket: bookit4pg-pro
  access_key_id: AKIAICR6FRQRFATSMPKQ
  secret_access_key: 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
